######################################################################
# Automatically generated by qmake (2.01a) Fr. Mai 18 18:53:47 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pnt2svg.cpp
