######################################################################
# Automatically generated by qmake (2.00a) Di Mai 3 02:44:22 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
SOURCES += texissor.cpp
DESTDIR = ../../bin
