######################################################################
# Automatically generated by qmake (2.00a) Di Mai 3 02:44:22 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

DEFINES += _USE_MATH_DEFINES=1

# Input
SOURCES += stars.cpp
DESTDIR = ../../bin
