######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 2 17:29:20 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
