######################################################################
# Automatically generated by qmake (2.01a) So Okt 19 09:48:08 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += iau2kml.cpp
