######################################################################
# Automatically generated by qmake (2.01a) Sa. Mai 19 00:05:30 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += pntdel.cpp
