######################################################################
# Automatically generated by qmake (2.01a) Sa. Mai 19 00:54:22 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += svgxmlhandler.h
SOURCES += pntreplace.cpp svgxmlhandler.cpp

QT += svg xml

