######################################################################
# Automatically generated by qmake (2.01a) J Aug 9 12:09:17 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../src/lib/Quaternion.h
SOURCES += dateline.cpp ../../src/lib/Quaternion.cpp
