######################################################################
# Automatically generated by qmake (2.01a) Mi 13. Aug 08:06:50 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

DEFINES += _USE_MATH_DEFINES=1

# Input
HEADERS += ../../src/lib/Quaternion.h ../../src/lib/marble_export.h
SOURCES += dateline.cpp ../../src/lib/Quaternion.cpp
