######################################################################
# Automatically generated by qmake (2.00a) So Jul 23 13:39:54 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += asc2kml.cpp
