######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 12 18:46:20 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += asc2kml.cpp
