.TH marble 1 "November 30, 2006" marble 1
.SH NAME
marble \- free 3D desk globe and world atlas
.SH SYNOPSIS
.B marble
.SH DESCRIPTION
This manual page documents briefly the
.B marble
program
.PP
\fBmarble\fP is a generic globe map widget, which provides general
information about the world geography.
.SH OPTIONS
.TP
.B \-\-timedemo
Will test the widgets performance and show the number of frames per 
second as a result.
.SH AUTHOR
marble was written by Torsten Rahn <rahn@kde.org>
