######################################################################
# Automatically generated by qmake (2.01a) L Iun 11 23:46:37 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += svgxmlhandler.h
SOURCES += svg2pnt.cpp svgxmlhandler.cpp

QT += svg xml