######################################################################
# Automatically generated by qmake (2.00a) Di Jan 3 18:35:44 2006
######################################################################

QT += xml
TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += svgxmlhandler.h
SOURCES += svg2pnt.cpp svgxmlhandler.cpp
DESTDIR = ../../bin
