######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 13 18:01:11 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += dso2kml.cpp
