######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 12 02:35:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += constellations2kml.cpp
